version: '3'
services:
  web:
    build: .
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=proekt

  redis:
    image: "postgres:alpine"
